name: Deploy Docker & Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-express-rest-api-example:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/node-express-rest-api-example:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/node-express-rest-api-example:latest
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node-express-rest-api-example:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/node-express-rest-api-example:latest
      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v1.2.0
        with:
          args: apply -f deployment.yaml,service.yaml
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
